version: '3'

services:

  nexus:
    # The version must be pinned: later version have random default 
    # password which make automation more complicated.
    image: sonatype/nexus3:3.16.2
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data

volumes:

  nexus-data:
    driver: local