Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.4"

  config.vm.define "oc" do |oc|
    oc.vm.network "private_network", ip: "192.168.32.10"
    oc.vm.hostname = "oc"
    oc.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
    oc.vm.provision "shell", path: "scripts/oc.sh"
  end

  config.vm.define "agent" do |agent|
    agent.vm.network "private_network", ip: "192.168.32.13"
    agent.vm.hostname = "agent"
    agent.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
    agent.vm.provision "shell", path: "scripts/agent.sh"
  end

  config.vm.define "master1" do |master1|
    master1.vm.network "private_network", ip: "192.168.32.11"
    master1.vm.hostname = "master1"
    master1.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
    master1.vm.provision "shell", path: "scripts/master.sh"
  end

  config.vm.define "master2" do |master2|
    master2.vm.network "private_network", ip: "192.168.32.12"
    master2.vm.hostname = "master2"
    master2.vm.provider "virtualbox" do |vb|
      vb.cpus = 1
      vb.memory = 1024
    end
    master2.vm.provision "shell", path: "scripts/master.sh"
  end

end
